services:
  - type: web
    name: shipsy-client
    runtime: static
    rootDir: client-panel
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: shipsy-courier-api
    runtime: node
    rootDir: client-panel
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TEAMPAFEX_EMAIL
        sync: false
      - key: TEAMPAFEX_PASSWORD
        sync: false
      - key: LOGIXMITRA_PUBLIC_KEY
        sync: false
      - key: LOGIXMITRA_PRIVATE_KEY
        sync: false
      - key: FSHIP_PUBLIC_KEY
        sync: false
      - key: FSHIP_PRIVATE_KEY
        sync: false
      - key: DELHIVERY_TOKEN
        sync: false
      - key: DELHIVERY_PICKUP_NAME
        value: BILAL
  - type: web
    name: shipsy-1admin
    runtime: static
    rootDir: admin-panel
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
